### ISSUE TITLE
Scoreboards

### ISSUE THREAD

**Issue by LavaisWatery** [LucidLLC/Teams-Issues#8]
#### IGN
> LavaisWatery

#### Expected behavior
> So when I joined the server today, I expected a scoreboard and some nametags to come along with it. 

#### Current behavior
> Nothing. I just get to pvp without my scoreboard and my combat timer. DepPReSSSing

#### Possible solutions (optional)
> https://github.com/bizarre/Glaedr or code your own like a fucking beast

#### Steps to reproduce (optional)
> Join the server

#### Other information (optional, screenshots)
> http://prntscr.com/lnvvpi

**Comment by rbrick** [comment]
Thank you for reporting. We are aware of the issue. 

Nametags are disabled on purpose until I get around to fixing them. They were written by me three years ago and had an memory allocation issue that I had only noticed after taking a closer look a few weeks ago (Having 400k strings in the string pool is rough). Through trying to fix it, I had inadvertently created another issue that I had not got around to fixing because I have been sick.

Scoreboard - Again, we're using custom code I wrote three years ago (updated this time to support 72 chars) and is the same one we use on the hub. @YoungOG claims it is my scoreboard API, yet says he had the same issue with other scoreboard APIs, soooooooooooooooooooooooooo...well you do the math. We'll get around to debugging this and get to the core of the problem.

EDIT: I love you @YoungOG, but your stubbornness can be annoying. ❤️ Sorry. No one hate on Calvin

**Comment by LavaisWatery** [comment]
The scoreboard is still broken.

**Comment by LavaisWatery** [comment]
wth

**Comment by dblucc** [comment]
Scoreboard is still broken!

**Comment by rbrick** [comment]
Scoreboard API is fine.
